pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = 'lifeloom'

include 'core'
include 'shell-desktop'
include 'shell-android'
include 'examples:demo-plugin'
include 'examples:demo-plugin-v2'
include 'examples:neighbor-plugin'
include 'system-plugins:permissions-plugin'
include 'system-plugins:time-plugin'
