plugins {
    id 'application'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release.set(11)
}

dependencies {
    implementation project(':core')
}

application {
    mainClass = 'dev.lifeloom.shell.desktop.Main'
    applicationDefaultJvmArgs = ['-Dfile.encoding=UTF-8']
}